---
title: "`r params$name` - `r params$date ` | Run report"
output: html_document
params: 
    km : NA
    time : NA
    pace : NA
    calories : NA
    date : NA
    run : NA #if multiple runs a day
    id : NA
    name : NA
    weight : NA
    latStart : NA
    longStart : NA
    latFinish : NA
    longFinish : NA
---
***
    Name : `r params$name `
    Weight : `r params$weight` Kg
    day of the run : `r params$date`
    distance : `r params$km` km
    Time : `r params$time` minutes
    Pace : `r params$pace` km/h
    Calories lost : `r params$calories`

```{r include = FALSE}
library(osrm)
```
```{r echo = FALSE, message=FALSE, warning = FALSE}
    route = osrmRoute(c(params$longStart,params$latStart), c(params$longFinish,params$latFinish), overview = 'full')
    # route_simple = osrmRoute(c(115.6813467,-32.0397559), c(150.3715249,-33.8469759), overview = 'simplified')
    route_summary = osrmRoute(c(params$longStart,params$latStart), c(params$longFinish,params$latFinish), overview = FALSE)

    
    leaflet() %>%
    addTiles() %>%
    addMarkers(c(params$longStart, params$longFinish), c(params$latStart, params$latFinish))  %>%
    
    addPolylines(route$lon, route$lat,
    # You can uncomment the lines below to display a bubble with the distance and the time estimated for this travel
    #             label = paste(round(route_summary[1]/60), 'hr - ', round(route_summary[2]), 'km'), 
    #             labelOptions = labelOptions(noHide = TRUE)
    )
```


